image: Visual Studio 2017
configuration: Release
environment:
  major_version: 1
  minor_version: 0
  patch_version: 0
version: '$(major_version).$(minor_version).$(patch_version).{build}'
dotnet_csproj:
  patch: true
  file: 'Morpher.WebService.V3.Adaptor\Morpher.WebService.V3.Adaptor.csproj'
  package_version: '$(major_version).$(minor_version).$(patch_version)'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- nuget restore
after_build:
- cmd: dotnet pack Morpher.WebService.V3.Adaptor/Morpher.WebService.V3.Adaptor.csproj --no-build -c Release
artifacts:
- path: 'Morpher.WebService.V3.Adaptor\**\*.nupkg'
  name: Nuget